GitHub Action workflow to validate changes to Helm chart with each applicable pull request.
Signed-off-by: Kevin Mellott <kevinmellott@northwesternmutual.com>
Co-authored-by: Kevin Mellott <kevin.r.mellott@gmail.com>

diff --git a/chart/templates/marquez/deployment.yaml b/chart/templates/marquez/deployment.yaml
--- a/chart/templates/marquez/deployment.yaml
+++ b/chart/templates/marquez/deployment.yaml
@@ -20,6 +20,53 @@ spec:
       labels: {{- include "common.labels.standard" . | nindent 8 }}
         app.kubernetes.io/component: marquez
     spec:
+      {{- if .Values.postgresql.enabled }}
+      # This init container is for avoiding CrashLoopback errors in the Marquez container because the PostgreSQL container is not ready
+      initContainers:
+        - name: wait-for-db
+          image: {{ include "common.images.image" (dict "imageRoot" .Values.postgresql.image "global" .Values.global) }}
+          imagePullPolicy: {{ .Values.postgresql.image.pullPolicy  }}
+          command:
+            - /bin/bash
+          args:
+            - -ec
+            - |
+              #!/bin/bash
+
+              set -o errexit
+              set -o nounset
+              set -o pipefail
+
+              . /opt/bitnami/scripts/libos.sh
+              . /opt/bitnami/scripts/liblog.sh
+              . /opt/bitnami/scripts/libpostgresql.sh
+
+              check_postgresql_connection() {
+                  echo "SELECT 1" | postgresql_remote_execute "$POSTGRES_HOST" "$POSTGRES_PORT" "$POSTGRES_DB" "$POSTGRES_USER" "$POSTGRES_PASSWORD"
+              }
+
+              info "Connecting to the PostgreSQL instance $POSTGRES_HOST:$POSTGRES_PORT"
+              if ! retry_while "check_postgresql_connection"; then
+                  error "Could not connect to the database server"
+                  return 1
+              else
+                  info "Connected to the PostgreSQL instance"
+              fi
+          env:
+            - name: POSTGRES_HOST
+              value: {{ include "marquez.database.host" . | quote }}
+            - name: POSTGRES_PORT
+              value: {{ include "marquez.database.port" . | quote }}
+            - name: POSTGRES_DB
+              value: {{ include "marquez.database.name" . | quote }}
+            - name: POSTGRES_USER
+              value: {{ include "marquez.database.user" . | quote }}
+            - name: POSTGRES_PASSWORD
+              valueFrom:
+                secretKeyRef:
+                  name: {{ include "marquez.postgresql.secretName" . }}
+                  key: {{ include "marquez.database.existingsecret.key" . }}
+      {{- end }}
       containers:
         - name: {{ .Chart.Name }}
           image: {{ include "marquez.image" . }}
